### ISSUE TITLE
'Print' font preference

### ISSUE THREAD

**Issue by sroebuck** [joelpt/sublimetext-print-to-html#3]
This is a feature request rather than a bug.

It would be handy to be able to specify the font to be used to render in the browser so that you can choose your favourite programming font for printouts.

**Comment by joelpt** [comment]
Good idea. Implemented! The new setting is "font_face".

I also added a "line_height" setting because I found with many fonts, the lines came out looking too scrunched together vertically using the browser's default setting.

I also added a "custom_css" setting which should give users more freedom over the exact styling they want used if they want to get their hands dirty.

**Comment by sroebuck** [comment]
Wow, that was quick!  Keep up the great work.
